const base = {
  id: 'mk',
  name: 'Mortal Kombat',
  soundDir: 'mk',
  statusLine: { label: '🩸', ctxBar: true },
  events: {
    stop: [
      'MK_Impressive.mp3', 
      'MK_Superb.mp3', 
      'MK_Outstanding.mp3', 
      'MK_Flawless_Victory.mp3', 
      'MK_Toasty.mp3', 
      'MK_Fight.mp3', 
      'MK_Kahn_All_To_Easy.mp3',
      "MK_Crowd_Clap.mp3",
      "MK_Impressive.mp3",
      "MK_Superb.mp3",
      "MK_Outstanding.mp3",
      "MK_Flawless_Victory.mp3",
      "MK_Jarek_Laugh.mp3",
      "MK_Kabal.mp3",
      "MK_Mileena.mp3",
      "MK_Quan_Chi.mp3",
      "MK_Rayden_Torpedo.mp3",
      "MK_Reptile_Wins.mp3",
      "MK_Shinnok.mp3",
      "MK_Sub_Zero.mp3",
      'MK_Laughter.mp3'
    ],
    sessionstart: ['MK_Test_Your_Might.mp3'],
    sessionend: ['MK_Laughter.mp3', 'MK_Shao_Kahn_Laugh.mp3', "MK_Hahaha_Dont_Make_Me_Laugh.mp3"],
    question: ['MK_Fatality.mp3', 'MK_Finish_Him.mp3', "MK_Scorpion_Come_Here.mp3", "MK_Scorpion_Get_Over_Here.mp3"],
    submit: [],
  },
  verbs: [
    "🕹️ Selecting fighter",
    "🔮 Choosing your destiny",
    "🦂 Getting over here!",
    "❄️ Training Lin Kuei",
    "👊 Fighting..",
    "☠️ Finishing him!",
    "👥 Noobing Saibot",
    "🌩️ Consulting Elder Gods",
    "🎩 Getting tricks from Shinnok",
    "🐉 Asking Shao Kahn nicely",
    "🧠 Reading Ermac's mind",
    "💀 Visiting the Netherrealm",
    "⚰️ Resurrecting Sindel",
    "🌍 Defending Earthrealm",
    "🧊 Freezing the codebase",
    "🔥 Barbecuing with Scorpion",
    "🤝🤝 Goro lending a hand x4",
    "🎭 Shapeshifting into a senior dev",
    "🎩 Throwing hat at the bug",
    "🚴 Cycling with Liu Kang",
    "⚡ Torpedoing through the codebase",
    "👸 Getting fan tips from Kitana",
    "🧙 Scheming with Quan Chi",
    "🤖 Cyrax & Sektor debating AI's future",
    "🕸️ Caught in Cyrax's net",
    "🚀 Launching to prod, Sektor style",
    "😤 Getting called pathetic by Shao Kahn"
  ],
};

export const mk = base;
