export const scProtoss = {
  id: 'sc-protoss',
  name: 'StarCraft: Protoss',
  soundDir: 'sc/protoss',
  statusLine: { label: '💎', ctxLabel: '🛸' },
  events: {
    stop: [
      'SC_Archon_The_Merging_Is_Complete.mp3',
      'SC_Arbiter_Dunad_wynn.mp3',
      'SC_Arbiter_J_tokoh_Zohl.mp3',
      'SC_Carrier_Instructions.mp3',
      'SC_Carrier_Your_Command.mp3',
      'SC_Corsair_Adun_Toridas.mp3',
      'SC_Dark_Archon_Must_Feed.mp3',
      'SC_Dark_Archon_We_Hear_You.mp3',
      'SC_Dark_Templar_Adun_Toridas.mp3',
      'SC_Dark_Templar_Ner_mah.mp3',
      'SC_Dark_Templar_Zerashk_Gulida.mp3',
      'SC_Dragoon_Galahoslos.mp3',
      'SC_Dragoon_I_Have_Returned.mp3',
      'SC_Dragoon_Input_Command.mp3',
      'SC_Dragoon_Lok_Pii.mp3',
      'SC_Dragoon_Metonah.mp3',
      'SC_Dragoon_Za_Khaladas.mp3',
      'SC_Probe_Pprwht01.mp3',
      'SC_Probe_Pprwht03.mp3',
      'SC_Protorss_Research_Complete.mp3',
      'SC_Protoss_Combeep0.mp3',
      'SC_Protoss_Upgrade.mp3',
      'SC_Reaver_Ptrrdy00.mp3',
      'SC_Scout_Standing_By.mp3',
      'SC_Scout_Teleport_Successful.mp3',
      'SC_Shuttle_Pshwht00.mp3',
      'SC_Shuttle_Pshwht01.mp3',
      'SC_Tassadar_Terrie_Khala.mp3',
      'SC_Templar_Khassar_detemplari.mp3',
      'SC_Templar_Your_Thoughts.mp3',
      'SC_Templar_Zerah_hah.mp3',
      'SC_Zealot_For_Adun.mp3',
      'SC_Zealot_Honor_Guide_Me.mp3',
      'SC_Zealot_My_Life_For_Aiur.mp3',
      'SC_Zeratul_Hmm.mp3',
      'SC_Zeratul_Khas_Naradahk.mp3',
      'SC_Zeratul_Your_Orders_Templar.mp3',
    ],
    sessionstart: [
      'SC_Carrier_Has_Arrived.mp3',
      'SC_Corsair_Ready_For_Battle.mp3',
      'SC_Tassadar_Yes_Executor.mp3',
      'SC_Artanis_For_Aiur.mp3',
      'SC_Artanis_Yes_Executor.mp3',
    ],
    sessionend: [
      'SC_Zeratul_I_Do_This_For_Aiur.mp3',
      'SC_Protoss_Probe_Ciao_Baby.mp3',
      'SC_Dark_Templar_Very_Well.mp3',
    ],
    question: [
      'SC_Protoss_Waiting.mp3',
      'SC_Dark_Templar_Im_Waiting.mp3',
      'SC_Dragoon_Awaiting_Instructions.mp3',
      'SC_Corsair_May_I_Be_Of_Service.mp3',
      'SC_Arbiter_We_Feel_Your_Presence.mp3',
    ],
    submit: [],
  },
  verbs: [
    '💎 Warping in probes',
    '⚡ Power overwhelming',
    '🔮 Channeling the Khala',
    '🛸 Carrier has arrived',
    '🙏 For Aiur!',
    '👁️ Zeratul sees all',
    '🌀 Arbiter distorting time',
    '🌩️ Templar storm incoming',
    '💠 Pylon powering up',
    '🏛️ Nexus under construction',
    '🕳️ Dark Templar in the shadows',
    '🤝 High Templar merging into Archon',
    '🎯 Reaver loading scarab',
    '🧘 Tassadar meditating on the context',
    '🔮 Khassar de Templari!',
    '😤 Zeratul: "Hmm."',
    '🌌 Scout teleporting to production',
    '🛡️ Zealot charging the codebase',
    '🔵 Dragoon input_command()',
    '🏗️ Expanding to the third',
    '⚔️ Charging with Zealots',
    '🔫 Cannon rushing',
    '⚡ Hallucinating a senior developer',
    '⚡ Zerah hah!',
    '⚡ Waiting for 75 energy',
    '🕳️ Templar-ing',
    '🐛 Releasing interceptors',
    '🌐 Disruption deployment',
    '🐌 Rescuing Dragoon from the ramp',
    '🔭 Sending probe'
  ],
};
