export const scTerran = {
  id: 'sc-terran',
  name: 'StarCraft: Terran',
  soundDir: 'sc/terran',
  statusLine: { label: '💎', ctxLabel: '☢️' },
  events: {
    stop: [
      'SC_Battlecruiser_All_Crews_Reporting.mp3',
      'SC_Goliath_Confirmed.mp3',
      'SC_SCV_Roger_That.mp3',
      'SC_SCV_Right_Away_Sir.mp3',
      'SC_SCV_Orders_Cap_n.mp3',
      'SC_Marine_Rock_and_Roll.mp3',
      'SC_Marine_Go_Go_Go.mp3',
      'SC_Marine_Lets_Move.mp3',
      'SC_Marine_Commander.mp3',
      'SC_Valkyrie_Perfect.mp3',
      'SC_Valkyrie_Of_Course_Mein_Herr.mp3',
      'SC_Ghost_Call_For_an_Exterminator.mp3',
      'SC_Ghost_Im_Here.mp3',
      'SC_Ghost_Finally.mp3',
      'SC_Ghost_Never_Know_What_Hi.mp3',
      'SC_Ghost_Reporting.mp3',
      'SC_Goliath_Comm-link_Online.mp3',
      'SC_Goliath_Go_Ahead_TACCOM.mp3',
      'SC_Medic_Where_Does_It_Hurt.mp3',
      'SC_Raynor_Any_Time_You_re_Ready.mp3',
      'SC_Battlecruiser_Set_a_Course.mp3',
      'SC_Dropship_Im_Listenin.mp3',
      'SC_Wraith_Standing_By.mp3',
      'SC_Job_S_Finished.mp3',
      'SC_All_Right.mp3',
      'SC_Dropship_Go_Ahead_HQ.mp3',
      'SC_Firebat_Lets_Burn.mp3',
      'SC_Firebat_Need_a_Light.mp3',
      'SC_Raynor_Here.mp3',
      'SC_Marine_Gimme_Something_To_Shoot.mp3',
      'SC_Battlecruiser_Good_Day_Commander.mp3',
      'SC_Medic_Prepped_And_Ready.mp3'
    ],
    sessionstart: [
      'SC_Battle_Cruiser_Operational.mp3',
      'SC_Battlecruiser_Good_Day_Commander.mp3',
      'SC_Firebat_You_Got_My_Attention.mp3',
      'SC_Kerrigan_Im_Ready.mp3',
      'SC_Medic_Prepped_And_Ready.mp3'
    ],
    sessionend: [
      'SC_Ghost_Im_Gone.mp3',
      'SC_Im_Gone.mp3',
      'SC_Duke_Alright_Then.mp3'
    ],
    question: [
      'SC_Base_Is_Under_Attack.mp3',
      'SC_I_Cant_build_there.mp3',
      'SC_Valkyrie_Dont_Keep_Me_Waiting.mp3',
      'SC_Dropship_Can_I_Take_Your_Order.mp3',
      'SC_Kerrigan_Im_Waitin_On_You.mp3',
    ],
    submit: [],
  },
  verbs: [
    '💎 Mining minerals',
    '⚒️ Building supply depot',
    '👨‍🚀 Training marines',
    '🔥 Roasting with a Firebat',
    '🚀 Battlecruiser operational',
    '👻 Ghost in the codebase',
    '🛸 Dropship inbound',
    '🔧 SCV good to go sir',
    '🎯 Sniper, lock and load',
    '🛡️ Bunker under construction',
    '🏗️ Lifting off',
    '📡 Hailing frequencies open',
    '🌌 Setting a course',
    '🤖 Goliath online',
    '💊 Medic! I need a medic!',
    '✈️ Wraith standing by',
    '☢️ Nuclear launch detected',
    '🔴 Supply blocked... as usual',
    '💰 Not enough tokens, obviously',
    '🍺 Raynor grabbing a drink first',
    '😤 Duke taking credit for the fix',
    '💣 Siege mode engaged',
    '🏰 Lifting off the command center',
    'Marine down! ...and another one',
    '🔬 Academy researching the bug',
    '📻 Adjutant, open a channel',
    '🎯 Calling in a nuke on the context',
    '👷 SCV rush! ...probably a bad idea',
  ],
};
