const base = {
  id: 'wc-human',
  name: 'Warcraft Human',
  soundDir: 'wc/human',
  events: {
    stop: [
      'Human_Hwrkdone_Work_Completed.mp3',
      'Human_Hyessir2_Yes_My_Lord.mp3',
      'Human_Hyessir3_As_You_Wish.mp3',
      'Human_Hyessir4_At_Once_Sire.mp3',
      'Human_Hshpyes1_AyeAye_Sir.mp3',
      'Human_Eyessir3_For_Alliance.mp3',
      'Human_Psyessr2_Righto.mp3',
      'Human_Psyessr3_Allright.mp3',
      'Human_Ewhat4_Your_Wish.mp3',
      'Human_Pspissd3_Now_What.mp3',
      'Human_Pspissd4_More_Work.mp3',
      'Human_Pspissd6_Dont_Wanna_Do_This.mp3',
      'Human_Hpissed4_I_Do_What_Work_To_Do.mp3',
      'Human_Hwhat5_MyLord.mp3',
      'Human_Dwhat1_What_Do_You_Want.mp3',
      'Human_Ewhat3_My_Soverign.mp3',
      'Human_Pswhat2_Milord.mp3',
      'Human_Pswhat4_Hello.mp3',
      'Human_Knwhat3_Sire.mp3',
      'Human_Pkwhat1_Your_Majesty.mp3',
      'Human_Wzwhat2_DoYou_Need_Assistance.mp3',
      'Human_Wzwhat3_Ur_Reauest.mp3',
      'Human_Knwhat3_Sire.mp3',
      'Human_Pkwhat1_Your_Majesty.mp3',
      'Human_Khwhat2_Whos_There.mp3',
      'Human_Knwhat3_Sire.mp3',
      'Human_Pkwhat1_Your_Majesty.mp3',
      'Human_Hwhat1_Your_Command.mp3',
      'Human_Wzpissd1_Busy_Man.mp3',
      'Human_Khpissd3_Are_You_Still_Here.mp3',
      'Human_Hready_Awaiting_Orders.mp3',
      'Human_Psready_To_Serve.mp3',
    ],
    sessionstart: [
      'Human_Gnpissd1_Hello_Sunny.mp3',
      'Human_Knready_Ready_To_Serve.mp3',
      'Human_Psready_To_Serve.mp3',
      'Human_Eready_I_Come_To_Serve.mp3',
    ],
    sessionend: [
      'Human_Pspissd5_Leave_Me_Alone.mp3',
      'Human_Pspissd7_Im_Not_Listening.mp3',
      'Human_Gnpissd5_GoodBye.mp3',
    ],
    question: [
      'Human_Epissed1_We_Must_Take_Action.mp3',
      'Human_Knpissd1_Need_Orders.mp3',
    ],
    submit: [],
  },
  verbs: [
    "⚔️ Training footmen",
    "🏰 Building keep",
    "🪄 Consulting the mage",
    "⚒️ Forging steel",
    "🛡️ Defending the alliance",
    "🫡 As you wish, milord",
    "⚔️ For the Alliance!",
    "📜 Your command is my will",
    "🙏 At once, sire",
    "😩 I don't wanna do this!",
    "💬 Yes, my lord",
    "💬 Righto!",
    "🫡 Awaiting orders",
    "❓ Who's there?",
    "💣 Hello, sunny! (boom)",
    "🐴 Need a hand? I have two!",
    "🏚️ More work?!",
    "🪓 Chop chop! ...wait, wrong faction",
    "🏗️ Upgrading to castle (soon)",
    "✨ Blessing this mess",
    "🔮 Reading the Tome of Power",
    "⛏️ Mining gold for tokens",
    "🧙 Consulting the mage tower",
    "⚡ Lightning Bolting",
    "🔥 Launching Fireball",
    "🌀 Flame Shielding",
    "🐌 Slowing time itself",
    "👻 Turning invisible (shh)",
    "🐑 Polymorphing the intern",
    "❄️ Blizzarding the battlefield",
    "⛏️ Looking for mine"
  ],
};

export const wcHuman = base;
