const base = {
  id: 'wc-orc',
  name: 'Warcraft Orc',
  soundDir: 'wc/orc',
  events: {
    stop: [
      'Orc_PeonBuildingComplete1.mp3',
      'Orc_Owrkdone_Work_Complete.mp3',
      'Orc_work_complete.mp3',
      'Orc_PeonYes3_WorkWork.mp3',
      'Orc_PeonYesAttack_Try.mp3',
      'Orc_acknowledge1_Ur_Command.mp3',
      'Orc_Oyessir1_ZugZug.mp3',
      'Orc_Oyessir2_Dabu.mp3',
      'Orc_Oyessir3_Loktar.mp3',
      'Orc_Oyessir4_Smabu.mp3',
      'Orc_Ogyessr2_Yes_Master.mp3',
      'Orc_Goyessr2_Certainly.mp3',
      'Orc_Goyessr3_Yes_Boss.mp3',
      'Orc_Kayessr2_ChopChop.mp3',
      'Orc_Dkyessr1_Of_Course_Master.mp3',
      'Orc_Dkyessr3_Hiia.mp3',
      'Orc_Oshpyes1_Ahoy.mp3',
      'Orc_Oshpyes3_Ur_The_Captain.mp3',
      'Orc_Tryessr3_You_The_Boss.mp3',
      'Orc_Ogpissd1_Yes_Dont_Want_To.mp3',
      'Orc_Ogpissd3_This_And_That_Way.mp3',
      'Orc_Opissed1_Whaat.mp3',
      'Orc_Opissed3_Missed_Me.mp3',
      'Orc_Oshppis2_Who_Wants_To_Sing.mp3',
      'Orc_Trpissd1_Got_Axe_For_You.mp3',
      'Orc_Ompissd2_We_Not_Brainless.mp3',
      'Orc_Odempis4_Good_Looking_For_Human.mp3',
      'Orc_Gopissd2_Kaboom.mp3',
      'Orc_Ogpissd2_Allright_And_Hungry.mp3',
      'Orc_Ogwhat1_Wha_What.mp3',
      'Orc_Ogwhat4_Master.mp3',
      'Orc_Owhat2_Zogtok.mp3',
      'Orc_Owhat3_Lordhook.mp3',
      'Orc_Owhat4_Wuu.mp3',
      'Orc_Owhat5_Laugh.mp3',
      'Orc_Kawhat1_Need_A_Hand.mp3',
      'Orc_Dkready_Im_Alive.mp3',
      'Orc_Pnready_Ready_To_Work.mp3',
      'Orc_Trready_New_Troll_Here.mp3',
      'Orc_Oready_Your_Command.mp3',
      'Orc_Ogready_We_Ready_Master.mp3',
      'Orc_PeonReady1.mp3',
      'Orc_Tewhat1_Greetings.mp3',
      'Orc_Trwhat1_You_Call_Me.mp3',
      'Orc_Trwhat2_DjDonks.mp3',
      'Orc_Dkwhat1_Yes.mp3',
      'Orc_select1.mp3',
      'Orc_PeonWhat2_Hh.mp3',
    ],
    sessionstart: [
      'Orc_PeonReady1.mp3',
      'Orc_Tewhat1_Greetings.mp3',
      'Orc_Opissed3_Missed_Me.mp3',
    ],
    sessionend: [
      'Orc_PeonPissed2_Bussy_Leaveme_Alone.mp3',
    ],
    question: [
      'Orc_Dkpissd1_Growing_Inpatient.mp3',
    ],
    submit: [],
  },
  verbs: [
    '⚔️ Training grunts',
    '⛏️ Sending peons',
    '🩸 Casting bloodlust',
    '⚒️ Building stronghold',
    '👹 Summoning ogres',
    '⛏️ Zug Zug',
    "⚔️ Lok'tar",
    "😈 When my work is finished, I'm coming back for you",
    '🪓 Chop chop!',
    "😩 I don't want to do this!",
    '💬 Zog tog',
    '💬 Dabu!',
    '🫡 You da boss',
    "❓ We're ready, master... I'm not ready!",
    '🧠 We not brainless',
    '👹 Feeding the ogres',
    '⛏️ Zug Zug-ging',
    '💣 Kaboom-ing',
    '🩸 Bloodlusting',
    '🧟 Raising the Dead',
    '🌪️ Summoning Whirlwind',
    '🔨 Work work-ing',
    '🪓 Axe-ing through problems',
    '🐗 Riding the wolf',
    '⛩️ Staring at the Dark Portal',
    '🤔 Growing impatient... (still waiting for GPU)',
    '🧂 Salting the prompt (oops)',
    '👹 Spawning ogres',
    '🪤 Setting Runes in the codebase',
    '👹 Two heads, one prompt',
    '🩸 Bloodlusting the build pipeline',
    '🔮 Casting Slow on the reviewer',
    '🪓 Got axe for this',
    '🔄 Dabu-ing without reading the prompt',
    '😤 Doing it anyway (terms: unread)',
    '⛏️ Mining gold for tokens',
    '⚡ Hasting before reading the docs',
    '💀 I\'m alive!',
    '🐑 Promoting peon to sheep',
    '🗺️ Exploring fog of war (rip)',
    '🐑 Sheep was a peon once (true story)',
    '🖱️ Clicking the peon',
    '🖱️ Clicking peon until he gets philosophical',
    '🌳 Peon stuck between two trees'
  ],
};

export const wcOrc = base;
